NS\Purearth\Stats\Signup:
    type: entity
    table: signup
    entityListeners:
        NS\PurearthBundle\Listeners\TimestampListener:
            preUpdate: [preUpdate]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        type:
            type: integer
            nullable: true
        wasTriggered:
            type: boolean
            nullable: true
